### ISSUE TITLE
react-native-ldk test framework

### ISSUE THREAD

**Issue by ovitrif** [synonymdev/react-native-ldk#216]
This task is to create a testing framework for `react-native-ldk`.

## Subtasks

- [ ] Create testing project for the Kotlin code
   - [x] #228
- [ ] ~~Review/update e2e tests~~
  ❌ `Cancelled`
- [ ] Create testing project for the Swift code and Add Swift tests
  ❌ `Cancelled`
